# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop

require: rubocop-rails

AllCops:
  Include:
    - '**/*.rb'
    - '**/config.ru'
    - '**/Rakefile'
    - 'Gemfile'
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'config/initializers/exportedScenarios.rb'
    - 'config/initializers/constants.rb'
    - 'config/initializers/games/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'client/node_modules/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: table
