GAMES[:crusaderkings] = {
    buy_link: 'http://www.greenmangaming.com/s/gb/en/pc/games/strategy/crusader-kings-ii/',
    site: 'gmg',
    title: 'Crusader Kings 2',
    background: 'crusaderkings.jpg',
    columns: {
        starting_duchy: {
            help: 'When starting, pick the duke of this duchy, a dejure vassal, or the dejure liege',
            title: 'Starting Duchy',
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Afar',
                :'Axum',
                :'Berbera',
                :'Damot',
                :'Gojjam',
                :'Gondar',
                :'Semien',
                :'Shewa',
                :'Wag',
                :'Alodia',
                :'Blemmyia',
                :'Makuria',
                :'Nobatia',
                :'Cyrenaica',
                :'Kabylia',
                :'Tripolitania',
                :'Tunis',
                :'Arabia',
                :'Damman',
                :'Medina',
                :'Nefoud',
                :'Oman',
                :'Sanaa',
                :'Alexandria',
                :'Aswan',
                :'Cairo',
                :'Damietta',
                :'Sinai',
                :'Ascalon',
                :'Galilee',
                :'Jerusalem',
                :'Oultrejourdain',
                :'Alger',
                :'Fes',
                :'Mauretania',
                :'Marrakech',
                :'Tangier',
                :'Tlemcen',
                :'Aleppo',
                :'Antioch',
                :'Damascus',
                :'Syria',
                :'Tripoli',
                :'Gauda',
                :'Nadia',
                :'Suhma',
                :'Vanga',
                :'Varendra',
                :'Jharkand',
                :'Kasi',
                :'Magadha ',
                :'Tirabhukti',
                :'Dahala',
                :'Ratanpur',
                :'Kamarupanagara',
                :'Para-Lauhitya',
                :'Sutiya',
                :'Daksina',
                :'Dandakaranya',
                :'Kalinga',
                :'Tosali',
                :'East Anglia',
                :'Essex',
                :'Hwicce',
                :'Kent',
                :'Lancaster',
                :'Mercia',
                :'Northumberland',
                :'Wessex',
                :'York',
                :'Connacht',
                :'Leinster',
                :'Meath',
                :'Munster',
                :'Ulster',
                :'Albany',
                :'Galloway',
                :'Lothian',
                :'Man',
                :'Moray',
                :'The Isles',
                :'Cornwall',
                :'Deheubarth',
                :'Gwynedd',
                :'Powys',
                :'Anatolia',
                :'Armeniacon',
                :'Charsianon',
                :'Cilicia',
                :'Paphlagonia',
                :'Thracesia',
                :'Trebizond',
                :'Armenia',
                :'Coloneia',
                :'Edessa',
                :'Mesopotamia',
                :'Karvuna',
                :'Moesia',
                :'Vidin',
                :'Bosnia',
                :'Croatia',
                :'Dalmatia',
                :'Slavonia',
                :'Abkhazia',
                :'Derbent',
                :'Kartli',
                :'Achaia',
                :'Adrianopolis',
                :'Aegean',
                :'Athens',
                :'Cibyrrhaeot',
                :'Cyprus',
                :'Dyrrachion',
                :'Epirus',
                :'Krete',
                :'Nikaea',
                :'Samos',
                :'Thessalonika',
                :'Thrace',
                :'Dioclea',
                :'Rashka',
                :'Apulia',
                :'Benevento',
                :'Calabria',
                :'Capua',
                :'Salerno',
                :'Sicily',
                :'Venice',
                :'Esztergom',
                :'Nyitra',
                :'Pecs',
                :'Pest',
                :'Temes',
                :'Transylvania',
                :'Ungvar',
                :'Moldau',
                :'Wallachia',
                :'Udayagiri',
                :'Vengi',
                :'Gangavadi',
                :'Kalyani',
                :'Nulambavadi',
                :'Raichur Doab',
                :'Lanka',
                :'Sinhala',
                :'Devagiri',
                :'Konkana',
                :'Nasikya',
                :'Rattapadi',
                :'Vidharba',
                :'Chera Nadu',
                :'Chola Nadu',
                :'Pandya Nadu',
                :'Tondai Nadu',
                :'Racakonda',
                :'Warangal',
                :'Aquitaine',
                :'Auvergne',
                :'Bourbon',
                :'Gascogne',
                :'Poitou',
                :'Toulouse',
                :'Brittany',
                :'Dauphiné',
                :'Provence',
                :'Savoy',
                :'Upper Burgundy',
                :'Anjou',
                :'Berry',
                :'Burgundy',
                :'Champagne',
                :'Normandy',
                :'Orleans',
                :'Valois',
                :'Badajoz',
                :'Cordoba',
                :'Granada',
                :'Murcia',
                :'Seville',
                :'Toledo',
                :'Aragon',
                :'Barcelona',
                :'Mallorca',
                :'València',
                :'Castille',
                :'Galicia',
                :'Asturias',
                :'León',
                :'Navarra',
                :'Algarve',
                :'Beja',
                :'Portucale',
                :'Austria',
                :'Bavaria',
                :'Carinthia',
                :'Tyrol',
                :'Bohemia',
                :'Moravia',
                :'Brabant',
                :'Flanders',
                :'Gelre',
                :'Holland',
                :'Baden',
                :'Brandenburg',
                :'Brunswick',
                :'Franconia',
                :'Köln',
                :'Meissen',
                :'Saxony',
                :'Swabia',
                :'Thüringia',
                :'Alsace',
                :'Lower',
                :'Luxembourg',
                :'Upper Lorraine',
                :'Ancona',
                :'Ferrara',
                :'Genoa',
                :'Latium',
                :'Lombardy',
                :'Modena',
                :'Pisa',
                :'Sardinia',
                :'Spoleto',
                :'Susa',
                :'Tuscany',
                :'Verona',
                :'Ghana',
                :'Mali',
                :'Songhay',
                :'Timbuktu',
                :'Kabulistan',
                :'Zabulistan',
                :'Baluchistan',
                :'Sistan',
                :'Dihistan',
                :'Khiva',
                :'Merv',
                :'Samarkand',
                :'Baghdad',
                :'Basra',
                :'Jazira',
                :'Kermanshah',
                :'Mosul',
                :'Tigris',
                :'Azerbaijan',
                :'Esfahan',
                :'Fars',
                :'Hamadan',
                :'Kerman',
                :'Khorasan',
                :'Tabaristan',
                :'Tabriz',
                :'Haritanaka',
                :'Kuru',
                :'Mathura',
                :'Vodamayutja',
                :'Anartta',
                :'Gurjara',
                :'Lata',
                :'Saurashtra',
                :'Jejakabhukti',
                :'Kanyakubja',
                :'Saryupara',
                :'Akara-Dasarna',
                :'Anupa',
                :'Avanti ',
                :'Gandhara',
                :'Lahore',
                :'Multan',
                :'Ajmer',
                :'Jangladesh',
                :'Maru',
                :'Medapata',
                :'Stravani',
                :'Bhakkar',
                :'Sauvira',
                :'Bjarmia',
                :'Perm',
                :'Ugra',
                :'Yugra',
                :'Belo Ozero',
                :'Moskva',
                :'Novgorod',
                :'Pskov',
                :'Rostov',
                :'Tver',
                :'Vladimir',
                :'Yaroslavl',
                :'Bryansk',
                :'Chernigov',
                :'Galich',
                :'Kiev',
                :'Pereyaslavl',
                :'Ryazan',
                :'Smolensk',
                :'Turov',
                :'Vitebsk',
                :'Volhynia',
                :'Holstein',
                :'Jylland',
                :'Sjælland',
                :'Skåne',
                :'Estonia',
                :'Finland',
                :'Karelia',
                :'Kola',
                :'Iceland',
                :'Jämtland',
                :'Orkney',
                :'Ostlandet',
                :'Trøndelag',
                :'Vestlandet',
                :'Bergslagen',
                :'Norrland',
                :'Småland',
                :'Uppland',
                :'Västergötland',
                :'Östergötland ',
                :'Alania',
                :'Azov',
                :'Itil',
                :'Kimak',
                :'Kipchak',
                :'Kirghiz',
                :'Sarkel',
                :'Sibir',
                :'Yaik',
                :'Cherson',
                :'Crimea',
                :'Syr Darya',
                :'Turkestan',
                :'Zhetysu',
                :'Bolghar',
                :'Cheremisa',
                :'Mari',
                :'Mordva',
                :'Courland',
                :'Lithuania',
                :'Livonia',
                :'Polotsk',
                :'Prussia',
                :'Samogitia',
                :'Yatvingia',
                :'Greater',
                :'Kuyavia',
                :'Lesser',
                :'Mazovia',
                :'Silesia',
                :'Mecklenburg',
                :'Pomeralia',
                :'Pomerania'
            ]
        },
        restrictions: {
            chance_of_multiple: 5,
            min: 1,
            max: 3,
            options: [
                :'No usurping',
                :"Do not use the 'Expell the Jewry' decision",
                :'Only marry lowborn',
                :'Never rebel against your liege',
                :'Always be honorable towards your family',
                :'Always be honorable towards your fellow vassals',
                :'Do not use factions',
                :'Always lead your army into battle',
                :'Always honor your alliances and actually help',
                :'Do not use mercenaries or holy orders',
                :'Ironman mode',
                :'Do your best to always play as a female',
                :'Always say yes when offered the chance to become a heretic',
                :'Always say yes when a vassal demands you transfer a vassal or de jure territory to them',
                :'Always say yes when your family requests a fief',
                :'Never honor alliances',
                :'Whenever a great holy war is called involving your religion, side with the enemy by declaring war on someone of your religion who is involved',
                :'Always say yes to culture conversions',
                :'As an emperor never hold more than one kingdom',
                :'As a king never hold more than one duchy',
                :'As a king have no duke level vassals unless it would put you over the vassal limit',
                :'No demanding religious conversion',
                :'Always say yes to faction demands',
                :'Always have a vassal educate your child',
                :'Always say yes to marriage requests',
                :'Always marry within your dynasty if possible',
                :'Never declare war against someone of your own religion',
                :'Never use holy wars',
                :'Never declare war on a claim below duchy level',
                :'Never declare war on a claim below kingdom level',
                :'Never sow dissent',
                :'Never improve religious relations',
                :'Never improve diplomatic relations',
                :'Never scheme',
                :'Never proselityze',
                :'No Retinues',
                :'Try to reach and maintain absolute crown authority',
                :'Try to reach and maintain autonomous vassals',
                :'Keep centralisation to a minimum',
                :'Keep centralisation as high as possible',
                :'Raise taxes as high as you can',
                :'Raise levies law as high as you can',
                :'Lower taxes as low as you can',
                :'Lower levies law as low as you can',
                :'Never retract titles',
                :'Never retract vassals',
                :'Never use the imprison action',
                :'Never release prisoners',
                :'Execute all prisoners',
                :'Release all prisoners',
                :'Always kill yourself when you become depressed',
                :'Throw a tournament every year',
                :'Throw a feast every year',
                :'Never surrender before -100% warscore',
                :'Never end a war before 100% or -100% warscore',
                :'Always have a plot',
                :'Always be a member of a faction',
                :'Never out a cheating spouse',
                :'Always out a cheating spouse',
                :'Always cheat on your spouse',
                :'Play on full speed',
                :"Don't pause",
                :"Play on full speed, and don't pause",
                :'Always marry below your rank',
                :'Always marry a ruler',
                :'Always marry your children to lowborn',
                :'Minimize your alliances',
                :'Whenever your spouse cheats, befriend their lover',
                :"Whenever your spouse cheats, seduce their lover's spouse",
                :"Whenever your spouse cheats, get a divorce",
                :'Always have an antipope'
            ]
        },
        goals: {
            sub_trees: [:target_religion, :target_empire],
            chance_of_multiple: :even,
            min: 1,
            max: 5,
            options: [
                {
                    :'Convert to the Target Religion' => {
                        title: 'Target Religion',
                        chance_of_multiple: 0,
                        min: 1,
                        max: 1,
                        options: [
                            :'Catholic',
                            :'Orthodox',
                            :'Miaphysite',
                            :'Nestorian',
                            :'Sunni',
                            :'Shia',
                            :'Ibadi',
                            :'Judaism',
                            :'Zoroastrian',
                            :'Hinduism',
                            :'Buddhism',
                            :'Jainism',
                            :'Germanic',
                            :'Reformed Germanic',
                            :'Reformed Slavic',
                            :'Tengri',
                            :'Reformed Tengri',
                            :'Reformed Romuva',
                            :'Suomenusko',
                            :'Reformed Suomenusko',
                            :'West African ',
                            :'Reformed West African',
                            :'Aztec',
                            :'Reformed Aztec',
                            :'Zunist',
                            :'Reformed Zunist',
                            :'Cathar',
                            :'Fraticelli',
                            :'Waldensian',
                            :'Lollard',
                            :'Monophysite',
                            :'Messalian ',
                            :'Bogomilist',
                            :'Monothelite',
                            :'Iconoclast',
                            :'Paulician',
                            :'Zikri',
                            :'Yazidi',
                            :'Druze',
                            :'Hurufi',
                            :'Mazdaki',
                            :'Samaritan',
                            :'Karaite',
                            :'Old Germanic',
                            :'Old Slavic',
                            :'Old Tengri',
                            :'Old Romuva',
                            :'Old Suomenusko',
                            :'Old West African',
                            :'Old Aztec',
                            :'Old Zunist'
                        ]
                    }
                },
                {
                    :'Own the Target Empire' => {
                        title: 'Target Empire',
                        chance_of_multiple: 0,
                        min: 1,
                        max: 1,
                        options: [
                            :'The Germanian Empire',
                            :'The Byzantine Empire',
                            :'The Italia Empire',
                            :'The Scandinavia Empire',
                            :'The Wendish Empire',
                            :'The Russian Empire',
                            :'The Tartarian Empire',
                            :'The Persian Empire',
                            :'The Carpathian Empire',
                            :'The Francia Empire',
                            :'The Hispania Empire',
                            :'The Arabian Empire',
                            :'The Britannia Empire',
                            :'The Mali Empire',
                            :'The Bengal Empire',
                            :'The Deccan Empire',
                            :'The Roman Empire',
                            :'The Latin Empire',
                            :'The Indian Empire',
                            :'The Holy Roman Empire'
                        ]
                    }
                },
                :'Kill the white stag',
                :'Own every Kingdom that is a part of the Brittania Empire',
                :'Reform a Pagan Religion',
                :'Work your way up from count to emperor',
                :'Set up an antipope',
                :'Sire a child with the inbred trait',
                :'As an Orthodox Christian hold Rome, Constantinople, Alexandria, Antioch, and Jerusalem',
                :'Be the highest contributor in a successful crusade for the Kingdom of Jerusalem',
                :'Successfully defend from a great holy war',
                :'Successfully defend from a holy war',
                :'As a ruler of non-india culture hold a King or Emperor title in India',
                :'Convert an entire religion to a heresy',
                :'Become the Saoshyant',
                :'Have the genius trait',
                :'Have the quick trait',
                :'Have the strong trait',
                :'Have the attractive trait',
                :'Convert Mecca to Hinduism, Jainism, or Buddhism',
                :'Acquire the Necronomicon',
                :'Have Robin Hood in your court',
                :'Become Samrat Chakravartin',
                :'Own the Francia, Germania, and Iberian Empires as a reformed pagan',
                :'Own one of the Francia, Germania, and Iberian Empires as an unreformed pagan',
                :'Own Rome as a pagan',
                :'Own Rome and Constantinople as a pagan',
                :'Own Rome as a Muslim',
                :'Conquer an opposing religions holy sites',
                :'Destroy the holy roman empire, in a start where it already exists',
                :'Destroy the Byzantine Empire',
                :"Form the Latin Empire and hold all of the Byzantine Empire's territory",
                :'Own Rome as a Miaphysite christian',
                :'Own Constantinople as a Miaphysite christian',
                :'Own Rome and Constantinople as a Miaphysite christian',
                :'Restore the borders of the Roman Empire',
                :'Convert Rome and Constantinople to any Indian Religion',
                :'Convert Rome and Constantinople to any one non-christian Religion',
                :'Convert all Christian Provinces to any non-Christian religions',
                :'Convert all Islamic Provinces to any non-Islamic religions',
                :'Convert all Hindu, Jainist, or Buddhist Provinces to any non-Hindu, non-Jainist, or non-Buddhist religions',
                :'Convert all Pagan Provinces to any non-Pagan religions',
                :'Convert all Zoroastrian Provinces to any non-Zoroastrian religions',
                :'Have 7 friends',
                :'Have 5 lovers',
                :'Contract Syphillis',
                :'Contract the Great Pox',
                :'Legitimise and then play as a bastard',
                :'Wipe out the Karling Family',
                :'Wipe out the Godwinson Family',
                :'Install an Antipope in Rome',
                :'Install an Antipope in Rome, and then replace him with another Antipope',
                :'Put a heretical pope in Rome',
                :'Have five heretic pentarchs',
                :'As a heretic, defend against a holy war from your parent religion',
                :'As a heretic, defend against a great holy war from your parent religion',
                :'Have 30 diplomacy',
                :'Have 30 martial',
                :'Have 30 stewardship',
                :'Have 30 intrigue',
                :'Have 30 learning',
                :'Forge a claim on another title, and then take it',
                :'Usurp an empire',
                :'Forge a claim on another title, and then inherit it on the same character',
                :'Go to war for a title you were going to inherit anyway',
                :'Defend against an adventurer',
                :'Have a holy order as your vassal',
                :'Give a holy order a kingdom',
                :'Give a holy order a duchy',
                :'As an emperor, have a kingdom level merchant republic as your vassal',
                :'As an emperor, have a kingdom level theocracy as your vassal',
                :'Create a faction and succesfully implement its goal',
                :'Create a faction and succesfully gain independence',
                :'Create a faction and succesfully put someone on the throne',
                :'Create a faction and succesfully change succession law',
                :'Create a faction and succesfully lower crown authority',
                :'Create a faction and succesfully put yourself on the throne',
                :'Create a faction and succesfully put your child on the throne',
                :'Create a faction and succesfully put your friend on the throne',
                :'Create a faction and succesfully put your lover on the throne',
                :'Create a faction and succesfully put your spouse on the throne',
                :'Create a faction, push your claim, and fail horribly',
                :'Die in a great holy war',
                :'Die in war',
                :'Become a crusader',
                :'Become a Mujahid',
                :'Go on a pilgramige',
                :'Go on a Hajj',
                :'As a non-Islamic character, bring Sayyid into your family tree',
                :'As a non-Islamic character, bring Mirza into your family tree',
                :'Become decedant',
                :'Have an Unworthy Court Chaplain',
                :'Become a Kinslayer',
                :'Be born in the purple',
                :'Go into hiding',
                :'Come out of hiding after killing the person who tried to kill you',
                :'Have all 7 Deadly Sins',
                :'Have all 7 Heavenly Virtues',
                :'Be a Falconer',
                :'Be a Poet',
                :'Become a Socializer',
                :'Become a Game Master',
                :'Become a Hedonist',
                :'Become a Duelist',
                :'Become a Hunter',
                :'Become a Strategist',
                :'Become a Administrator',
                :'Become a Architect',
                :'Become a Gardener',
                :'Become a Master Schemer',
                :'Become an Impaler',
                :'Become a Master Seducer',
                :'Become Celibate',
                :'Become a Master Seductress',
                :'Become a Scholar',
                :'Become a Theologian',
                :'Become a Mystic',
                :'Become scarred',
                :'Become a lunatic and speak to god',
                :'Become an Elusive Shadow',
                :'Become a Grey Eminence',
                :'Become Midas Touched',
                :'Become a Brilliant Strategist',
                :'Become a Mastermind Theologian',
                :'Take a title in a holy war and then convert to the opposing religion',
                :"Take a title in a holy war and convert the title's de jure provinces to your religion",
                :'Be excommunicated',
                :'Pay the pope to forgive your sins',
                :'Win a war against an enemy twice your size whilst independent',
                :'Win a war against an enemy with the help of two allies',
                :'Conquer an ally',
                :'Become friends with your liege',
                :'Become the lover of your liege',
                :'Raise someone of lowborn birth to the throne of a kingdom',
                :'Seduce a bishop',
                :'Seduce a prince-bishop',
                :'Seduce a king-bishop',
                :'Play as the seventh child',
                :'Play as the seventh child of a seventh child',
                :'Assassinate your wife',
                :'Assassinate your father',
                :'Assassinate your mother',
                :'Assassinate your brother',
                :'Assassinate your liege',
                :'Assassinate a vassal',
                :'Assassinate a religious head',
                :'Assassinate someone of no importance',
                :'Befriend your liege, and then assassinate him',
                :"Become your liege's lover, and then assassinate him",
                :'Assassinate someone planning an adventurer into your territory',
                :"Defend against your liege's tyranny",
                :'Defeat a vassal as they attempt to defend against your tyranny',
                :'Defend against a rebellion',
                :'Have your liege be both your friend and your lover',
                :"Become your liege's enemy",
                :'Defeat your liege in a duel',
                :'Be in a homosexual relationship',
                :'Have a dog',
                :'Survive depression',
                :'Live to 90',
                :'Play a full game',
                :'Convert to Aztec',
                :'Convert the de jure provinces of a European Empire to Aztec',
                :'Own Rome as an Aztec',
                :'Own Constantinople as an Aztec',
                :'Own a province in India as an Aztec',
                :'Sacrifice the pope as a pagan or Kali worshipper',
                :'Sacrifice a king as a pagan or Kali worshipper',
                :'Sacrifice an emperor as a pagan or Kali worshipper'
            ]
        },
    }
}