GAMES[:dark_souls] = {
    buy_link: 'http://www.greenmangaming.com/s/gb/en/pc/games/action/dark-souls-prepare-die-edition/',
    site: 'gmg',
    title: 'Dark Souls',
    generator_title: 'Character',
    background: 'darksouls.jpg',
    columns: {
        right_handed_weapon: {
            help: 'If you get a special weapon, use a weapon of the same class until you acquire it',
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :Axe,
                :Greataxe,
                :Hammer,
                :'Great Hammer',
                :Spear,
                :Halberd,
                :Bow,
                :Crossbow,
                :'Straight Sword',
                :Greatsword,
                :'Ultra Greatsword',
                :'Curved Sword',
                :'Curved Greatsword',
                :'Thrusting Sword',
                :Katana,
                :Dagger,
                :Gauntlet,
                :Whip,
                :'Fists',
                :'Skull Lantern',
                :Catalyst,
                :Talisman,
                :'Pyromancy Flame',
                :'Small Shield',
                :'Medium Shield',
                :Greatshield,
                :'Broken straight sword',
                :'Gargoyle Tail Axe',
                :'Golem Axe',
                :'Black Knight Greataxe',
                :'Blacksmith Giant Hammer',
                :'Demon\'s Great Hammer',
                :'Dragon Tooth',
                :'Smough\'s Hammer',
                :'Demon\'s Spear',
                :'Dragonslayer Spear',
                :'Moonlight Butterfly Horn',
                :'Silver Knight Spear',
                :'Lifehunt Scythe',
                :'Giant\'s Halberd',
                :'Black Knight Halberd',
                :'Gough\'s Greatbow',
                :'Darkmoon Bow',
                :'Dragonslayer Greatbow',
                :'Avelyn',
                :'Astora’s Straight Sword',
                :'Drake Sword',
                :'Darksword',
                :'Sunlight Straight Sword',
                :'Abyss Greatsword',
                :'Great Lord Greatsword',
                :'Greatsword of Artorias',
                :'Man-Serpent Greatsword',
                :'Black Knight Greatsword',
                :'Demon Great Machete',
                :'Quelaag\'s Furysword',
                :'Gravelord Sword',
                :'Velka\'s Rapier',
                :'Priscilla\'s Dagger'
            ]
        },
        left_handed_weapon: {
            help: 'If your primary weapon is two handed, skip this',
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :Axe,
                :Greataxe,
                :Hammer,
                :'Great Hammer',
                :Spear,
                :Halberd,
                :Bow,
                :Crossbow,
                :'Straight Sword',
                :Greatsword,
                :'Ultra Greatsword',
                :'Curved Sword',
                :'Curved Greatsword',
                :'Thrusting Sword',
                :Katana,
                :Dagger,
                :Gauntlet,
                :Whip,
                :'Fists',
                :'Skull Lantern',
                :Catalyst,
                :Talisman,
                :'Pyromancy Flame',
                :'Small Shield',
                :'Medium Shield',
                :Greatshield,
                :'Small Shield',
                :'Medium Shield',
                :Greatshield,
                :'Small Shield',
                :'Medium Shield',
                :Greatshield,
                :'Small Shield',
                :'Medium Shield',
                :Greatshield,
                :'Small Shield',
                :'Medium Shield',
                :Greatshield,
                :'Small Shield',
                :'Medium Shield',
                :Greatshield,
                :'Small Shield',
                :'Medium Shield',
                :Greatshield,
                :'Small Shield',
                :'Medium Shield',
                :Greatshield,
                :'Buckler',
                :'Caduceus Round Shield',
                :'Cracked Round Shield',
                :'Effigy Shield',
                :'Leather Shield',
                :'Plank Shield',
                :'Red and White Round Shield',
                :'Small Leather Shield',
                :'Target Shield',
                :'Warrior\'s Round Shield',
                :'Balder Shield',
                :'Black Knight Shield',
                :'Bloodshield',
                :'Caduceus Kite Shield',
                :'Crest Shield',
                :'Dragon Crest Shield',
                :'East-West Shield',
                :'Gargoyle\'s Shield',
                :'Grass Crest Shield',
                :'Heater Shield',
                :'Hollow Soldier Shield',
                :'Iron Round Shield',
                :'Knight Shield',
                :'Large Leather Shield',
                :'Sanctus',
                :'Silver Knight Shield',
                :'Spider Shield',
                :'Sunlight Shield',
                :'Tower Kite Shield',
                :'Wooden Shield',
                :'Black Iron Greatshield',
                :'Bonewheel Shield',
                :'Cleansing Greatshield',
                :'Eagle Shield',
                :'Giant Shield',
                :'Greatshield of Artorias',
                :'Havel\'s Greatshield',
                :'Stone Greatshield',
                :'Tower Shield',
                :'Crystal Ring Shield',
                :'Crystal Shield',
                :'Spiked Shield',
                :'Pierce Shield',
                :'Dark Hand'
            ]
        },
        rings: {
            help: 'Do not equip any other rings, except those required to advance through the story',
            chance_of_multiple: 0,
            min: 2,
            max: 2,
            options: [
                :'Bellowing Dragoncrest Ring',
                :'Bloodbite Ring',
                :'Blue Tearstone Ring',
                :'Calamity Ring ',
                :'Your Covenant Ring',
                :'Cloranthy Ring',
                :'Covetous Gold Serpent Ring',
                :'Covetous Silver Serpent Ring',
                :'Cursebite Ring',
                :'Darkmoon Seance Ring',
                :'Dark Wood Grain Ring',
                :'Dusk Crown Ring',
                :'East Wood Grain Ring',
                :'Flame Stoneplate Ring',
                :'Havel\'s Ring',
                :'Hawk Ring',
                :'Hornet Ring',
                :'Leo Ring',
                :'Lingering Dragoncrest Ring',
                :'Orange Charred Ring',
                :'Poisonbite Ring ',
                :'Rare Ring of Sacrifice',
                :'Red Tearstone Ring',
                :'Ring of Favor and Protection',
                :'Ring of Sacrifice',
                :'Ring of Steel Protection',
                :'Ring of the Evil Eye',
                :'Ring of the Sun\'s Firstborn',
                :'Rusted Iron Ring',
                :'Slumbering Dragoncrest Ring',
                :'Speckled Stoneplate Ring',
                :'Spell Stoneplate Ring',
                :'Thunder Stoneplate Ring',
                :'White Seance Ring',
                :'Wolf Ring'
            ]
        },
        weapon_upgrade_path: {
            help: 'Ignore this if you are assigned a special weapon',
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :Normal,
                :Lightning,
                :Crystal,
                :Divine,
                :Occult,
                :Magic,
                :Enchanted,
                :Fire,
                :Chaos
            ]
        },
        armour_set: {
            help: 'Do not exceed your assigned set\'s weight before acquiring it. This does not apply for non-specific sets.',
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Whenever you find a new piece of armor, you must equip it.',
                :'Use only the first armour you find for each slot',
                :'Your starting armour',
                :'Light armour',
                :'Medium armour',
                :'Heavy armour',
                :'Antiquated Set',
                :'Big Hat\'s Set',
                :'Black Set',
                :'Black Sorcerer Set',
                :'Chain Set',
                :'Chester\'s Set',
                :'Crimson Set',
                :'Dingy Set',
                :'Gold-Hemmed Black Set',
                :'Great Lord Set',
                :'Hollow Soldier Set',
                :'Hollow Thief\'s Set',
                :'Hollow Warrior Set',
                :'Lord\'s Blade',
                :'Maiden Set',
                :'Moonlight Set',
                :'Painting Guardian Set',
                :'Shadow Set',
                :'Witch Set',
                :'Xanthous Set',
                :'Adventurer\'s Set',
                :'Balder Set',
                :'Black Knight Set',
                :'Brass Set',
                :'Catarina Set',
                :'Channeler\'s Set',
                :'Cleric Set',
                :'Crystalline Set',
                :'Dark Set',
                :'Eastern Set',
                :'Elite Knight Set',
                :'Favor Set',
                :'Gough\'s Set',
                :'Iron Set',
                :'Ornstein\'s Set',
                :'Paladin Set',
                :'Set of Artorias',
                :'Silver Knight Set',
                :'Steel Set',
                :'Thorns Set',
                :'Black Iron Set',
                :'Giant Set',
                :'Golem Set',
                :'Guardian Set',
                :'Havel\'s Set',
                :'Smough\'s Set',
                :'Stone Set',
                :'No armour'
            ]
        },
        challenge: {
            chance_of_multiple: 15,
            min: 1,
            max: 5,
            options: [
                :'Do not skip your secondary weapon if your primary is two handed, wield both',
                :"Don't level up",
                :"Don't level past 10",
                :"Don't level past 11",
                :"Don't level past 20",
                :"Don't level past 30",
                :"Don't level past 40",
                :"Don't level past 43",
                :"Don't level past 50",
                :"Don't level past 60",
                :'Be human at all times, if you cannot regain your humanity without leaving the bonfire. Game Over.',
                :'Kill all killable NPCs upon meeting them, unless required to complete quest challenge',
                :'Complete Anastacia, Guardian of the Firelink Shrine\'s quest chain',
                :'Complete Big Hat Logan\'s quest chain',
                :'Complete Dusk of Oolacile\'s quest chain',
                :'Complete Knight Laurtrec of Carim\'s quest chain',
                :'Complete Laurentius of the Great Swamp\'s quest chain',
                :'Complete Patches the Hyena\'s quest chain',
                :'Complete Petrus of Thorolund\'s quest chain',
                :'Complete Quelaana the Witch of Iizalith\'s quest chain',
                :'Complete Siegmeyer of Catarina\'s quest chain',
                :'Complete Solaire of Astoria\'s quest chain',
                :'Complete all NPC quest chains',
                :'Kill all bosses',
                :'If you die, game over (except mandatory deaths)',
                :'Don\'t recover your souls or humanity',
                :'Never use estus',
                :'Do not use estus until you have at least 10 uses available',
                :'Never use more than one estus before recharging',
                :'Never use more than two estus before recharging',
                :'Never use estus during a boss fight',
                :'Only use Estus during boss fights',
                :'Reach the max rank in your assigned covenant',
                :'Do not teleport between bonfires',
                :'Only use bonfires when you die',
                :'Torso armour only',
                :'Head armour only',
                :'Foot armour only',
                :'Gauntlet armour only',
                :'Only use one ring',
                :'No rings',
                :'No farming for humanity',
                :'Pick two stats, only level those stats',
                :'Only level vitality',
                :'Only level endurance',
                :'Only level strength',
                :'Only level dexterity',
                :'Only level resistance',
                :'Only level intelligence',
                :'Only level faith',
                :'Only level attunement',
                :'No summoning phantoms for assistance',
                :'Complete the game without resting at a bonfire',
                :'No HUD',
                :'Do not upgrade your weapon',
                :'Do not upgrade your weapon past +1',
                :'Do not upgrade your weapon past +5',
                :'Collect every piece of armour in the game',
                :'Collect every weapon in the game',
                :'You cannot beat a boss until you have helped someone else beat it first',
                :'Only level your lowest stat',
                :'Find out what the pendant does',
                :'Ignite no bonfires',
                :'Level no stat past 15',
                :'Do not level vitality past 15',
                :'Do not level endurance past 15',
                :'Do not level strength past 15',
                :'Do not level dexterity past 15',
                :'Do not level resistance past 15',
                :'Do not level faith past 15',
                :'Do not level attunement past 15',
                :'Level no stat past 30',
                :'Do not level vitality past 30',
                :'Do not level endurance past 30',
                :'Do not level strength past 30',
                :'Do not level dexterity past 30',
                :'Do not level resistance past 30',
                :'Do not level faith past 30',
                :'Do not level attunement past 30',
                :'Keep your stats below the requirement for your assigned weapons (unless you start above it)',
                :'No rolling',
                :"Replace your assigned armour set's helmet with a mimic chest helmet",
                :"Replace your assigned armour set's helmet with a boar head helmet",
                :'Keep 10000 liquid souls at all times, only spend souls above that level',
                :'Keep 50000 liquid souls at all times, only spend souls above that level',
                :'Keep 100000 liquid souls at all times, only spend souls above that level',
                :'Only do damage via kicking',
                :'Only level up 5 times per area. This does not roll over, once you advance you lose your chance',
                :'Only level up once per area. This does not roll over, once you advance you lose your chance',
                :'Defeat someone in pvp before advancing past each area',
                :'Skip all optional areas',
                :'Skip all optional bosses',
                :'Beat each boss in under 2 minutes, if you exceed that timer you must leave and try again',
                :'You have five attempts on each boss, if you run out and the boss is not optional for advancement, game over',
                :'You have one attempt on each boss, if you fail and the boss is not optional for advancement, game over',
                :'You have two attempts on each boss, if you run out and the boss is not optional for advancement, game over'
            ]
        },
        primary_covenant: {
            help: 'This is your primary covenant. You can swap, but only to complete challenges. You must swap back as soon as possible.',
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Blade of the Darkmoon',
                :'Chaos Servant',
                :'Darkwraith',
                :'Forest Hunter',
                :'Gravelord Servant',
                :'Path of the Dragon',
                :'Princess\'s Guard',
                :'Warrior of Sunlight',
                :'Way of White',
            ]
        },
        starting_class: {
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Warrior',
                :'Knight',
                :'Wanderer',
                :'Thief',
                :'Bandit',
                :'Hunter',
                :'Sorcerer',
                :'Pyromancer',
                :'Cleric',
                :'Deprived'
            ]
        },
        starting_gift: {
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'None',
                :'Goddess\'s Blessing',
                :'Black Firebomb',
                :'Twin Humanities',
                :'Binoculars',
                :'Pendant',
                :'Master Key',
                :'Tiny Being\'s Ring',
                :'Old Witch\'s Ring'
            ]
        }
    }
}