GAMES[:orcs_must_die] = {
    buy_link: 'http://www.amazon.com/gp/product/B008IHKNA4/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=B008IHKNA4&linkCode=as2&tag=scen-gen-20&linkId=7XCYIPZDUXIH7GFF',
    site: 'amazon',
    title: 'Orcs Must Die',
    generator_title: 'Loadout',
    background: 'omd1.jpg',
    added: Date.strptime('20150323',"%Y%m%d"),
    last_updated: Date.strptime('20150323',"%Y%m%d"),
    columns: {
        traps_and_weapons: {
            help: "If you haven't unlocked a trap or weapon, replace it with your own choice",
            chance_of_multiple: 0,
            min: 9,
            max: 9,
            options: [
                :'Spike Trap',
                :'Tar Trap',
                :'Arrow Wall',
                :'Boom Barrel',
                :'Spring Trap',
                :'Barricade',
                :'Wall Blades',
                :'Pounder',
                :'Steam Trap ',
                :'Push Trap',
                :'Swing Mace',
                :'Decoy',
                :'Autoballista',
                :'Grinder',
                :'Coin Forge',
                :'Spore Mushroom',
                :'Shock Zapper',
                :'Floor Scorcher',
                :'Alchemist Satchel',
                :'Bladestaff',
                :'Flame Bracers',
                :'Ice Amulet',
                :'Lightning Ring',
                :'Vampiric Guantlets',
                :'Wind Belt'
            ]
        },
        level: {
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :"The Hallway",
                :"The Fork",
                :"The Corner",
                :"The Baths",
                :"Runner's Alley",
                :"Overpass",
                :"Twin Halls",
                :"Lunch Break",
                :"The Stream",
                :"Sludge Hole",
                :"Chaos Chamber",
                :"Chokepoint",
                :"The Arena",
                :"The Balcony",
                :"The Tower",
                :"The Library",
                :"The Bridge",
                :"Killing Fields",
                :"Rebirth",
                :"Gateway",
                :"Hard Climb",
                :"The Squeeze",
                :"Stairs of Doom",
                :"Finale",
                :"Double Trouble",
                :"Reverse Tower",
                :"The Pit",
                :"Triple Down",
                :"Great Gorge"
            ]
        }
    }
}