GAMES[:terraria] = {
    buy_link: 'http://store.steampowered.com/app/105600/',
    site: 'terraria',
    title: 'Terraria',
    generator_title: 'Challenge',
    background: 'terraria.jpg',
    columns: {
        main_base_biome: {
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :"The Purity/Forest",
                :"Ice/Tundra",
                :"Desert",
                :"Jungle",
                :"Crimson/Corruption, NPC can live elsewhere.",
                :"Ocean",
                :"Hallow, when it spawns.",
                :"The Underworld",
                :"Sky Islands",
            ]
        },
        restrictions: {
            chance_of_multiple: 5,
            min: 1,
            max: 4,
            options: [
                :"You may not use anything that deals Melee Damage",
                :"You may not use anything that deals Ranged Damage",
                :"You may not use anything that deals Magic Damage",
                :"You may not use anything that deals Summoner Damage",
                :"No use of any NPC. (Exception for Old Man)",
                :"No beds",
                :"No doors",
                :"No selling of gold animals",
                :"No planting",
                :"No planting trees",
                :"No armour, save for Angler Armor",
                :"You may not reforge",
                :"You cannot mine obsidian",
                :"Your primary weapons are Melee",
                :"Your primary weapon are Ranged",
                :"Your primary weapons are Magic",
                :"Your primary weapon are Minions/Staffs",
                :"Your primary weapons are Throwing Items",
                :"Your only weapons are Melee",
                :"Your only weapons are Ranged",
                :"Your only weapons are Magic",
                :"Your only weapons are Minions",
                :"Make and wear a fishbowl, never take it off, yet always have Neptune's Shell on",
                :"No wood of any kind (save for spooky) unless absolutely necessary",
                :"No iron/lead unless absolutely necessary",
                :"No gold/platinum unless absolutely necessary",
                :"No buckets",
                :"No potions",
                :"No wiring",
                :"No manmade minecarts",
                :"No lava",
                :"Build only using dirt",
                :"Build only using stone",
                :"Build only using marble",
                :"Build only using wood",
                :"Build only using obsidian",
                :"Build only using mud",
                :"You may not touch water",
                :"Use only ebon/shadewood",
                :"Use only boreal wood",
                :"Use only palm wood",
                :"Use only rich mahogany (jungle wood)",
                :"No rope or chains placed",
                :"Cannot build with mud",
                :"Cannot build with wood",
                :"Cannot build with stone",
                :"Cannot build with dirt",
                :"No health potions",
                :"Minimize jumping",
                :"All resources must be used as soon as possible",
                :"Use no storage except your inventory",
                :"Never have more than one of each tool at a time",
                :"Never have more than one axe at a time",
                :"Never have more than one sword at a time",
                :"Never have more than one pickaxe at a time",
                :"Play on hardcore",
                :"Play on Expert Mode",
                :"You have one night above ground. As soon as night falls you must move everything underground, seal yourself off and never return",
                :"All plants must be grown above ground",
                :"All plants must be grown below ground",
                :"Never retreat from enemies",
                :"Only use weapons from chests",
                :"Only use accessories from chests",
                :"Only use weapons from drops",
                :"Only use accessories from drops",
                :"Prioritise armor from drops",
                :"You may not travel above ground, tunnel everywhere (except for entering the dungeon for the first few times)",
                :"Only 30 torches may exist in the world or your inventory at a time. If you find more, leave them",
                :"Build everything out in the open. No walls. No doors. No building underground. No fences. Don't try and be clever",
                :"Build no base, live in villages",
                :"Do not kill Slimes (save for king slime and his spiked slimes.)",
                :"Do not kill Zombies",
                :"Do not kill Animals, such as bunnies",
                :"Whenever you die, destroy 10 of any kind of soul in hardmode",
                :"Do not retrieve your items on death, and put mediumcore on",
                :"No light pets or normal pets",
                :"You cannot fish",
            ]
        },
        goals: {
            chance_of_multiple: 75,
            min: 1,
            max: 6,
            options: [
                :"Fill a chest with Souls of Sight, Might, or Fright",
                :"Fill a chest with Luminite",
                :"Fill a chest with Wood",
                :"Fill a chest with Fish",
                :"Fill a chest with Lava buckets",
                :"Create an artificial lake bigger than 300 blocks",
                :"Create an artificial lake and build a base under its surface",
                :"Create an artificial lake and build a base above its surface",
                :"Collect one of every Tree",
                :"Collect one of every Bar (like a copper bar)",
                :"Collect one of every Block, unless the world doesn't have it.",
                :"Collect every pet in the game",
                :"Collect every light pet in the game",
                :"Collect one of every Wood",
                :"Make the whole world Corrupted, Crimson-ized, or Hallowed",
                :"Kill all optional bosses, those being: King Slime, Queen Bee and Duke Fishron",
                :"Kill all bosses.",
                :"Kill the Dungeon Guardian",
                :"Kill the Moon Lord",
                :"Kill Duke Fishron",
                :"Renovate a Underground/Ruined House",
                :"Renovate a Sky Island",
                :"Renovate a part of The Dungeon",
                :"Renovate a Living Tree",
                :"Renovate a part of The Jungle Temple",
                :"Build a Pyramid",
                :"Build a Temple",
                :"Build a Giant Airship",
                :"Build a Castle",
                :"Build an Underground Base",
                :"Build a Nuclear Bunker stocked with food to last for years",
                :"Build an Underwater Base",
                :"Build an Underwater Zoo stocked with one of every possible animal",
                :"Build a Zoo Stocked with one of every possible animal",
                :"Build a working wire CPU",
                :"Build a working train station linking several bases across multiple biomes",
                :"Build a Steve Statue, as a homage to Minecraft",
                :"Build a Water-Related-Labyrinth",
                :"Build a scene or level out of a different video game of your choosing.",
                :"Build a Large Farm",
                :"Build a Sky Fortress that provides all the resources you require to Survive",
                :"Build a Pirate Ship",
                :"Build a Space Ship",
                :"Build a Volcano",
                :"Build a Corrupted, Crimsonized, or Hallowed Living Tree",
                :"Build a Tree House",
                :"Build a town for all the NPC's",
                :"Build a wall for protection around a village",
                :"Build your neighbourhood",
                :"Build a national monument",
                :"Build your real life house",
                :"Build any kind of art that you'd like to build",
                :"Beat the Moon Lord on hardcore",
                :"Reach Hardmode in 10 days",
                :"Kill all Corruption/Crimson",
                :"Kill all biomes, and make them the Purity/Forest",
                :"Clear out a Mineshaft",
                :"Create these Biomes in miniature: Desert, Tundra, Forest/Purity, Crimson, Jungle, Corruption, Ocean",
                :"Farm every plant in the game",
                :"Kill all 3 mech bosses at the same time",
                :"Discover 10 Ruined Houses (not in the underworld)",
                :"Discover a Sky Island and a Sky Lake",
                :"Create a Library",
                :"Create a set of Vortex Armor",
                :"Create a set of Solar Armor",
                :"Create a set of Nebula Armor",
                :"Create a set of Stardust Armor",
            ]
        }
    }
}
