genders = [
    :Male,
    :Female
]

hair_colours = [
    :Blonde,
    :Brown,
    :Brunette,
    :Black,
    :Red
]

eye_colours = [
    :Brown,
    :Blue,
    :Green,
    :Grey,
    :Yellow,
    :Red
]

styles = [
    :Smart,
    :Skater,
    :Goth,
    :Preppie,
    :Techie,
    :Serious,
    :Suited,
    :Minimalist,
    :Crazy,
    :Colorful,
    :Boring,
    :"Classic clothes",
    :"80s clothes",
    :Modern,
    :Unfashionable,
    :Fashionable,
    :"Always wears work clothes",
    :"As nude as feasibly possible"
]

traits = [
    :"Absent-Minded",
    :"Artistic",
    :"Avant Garde",
    :"Bookworm",
    :"Can't Stand Art",
    :"Computer Whiz",
    :"Eccentric",
    :"Gatherer",
    :"Excitable",
    :"Genius",
    :"Green Thumb",
    :"Handy",
    :"Insane",
    :"Natural Cook",
    :"Neurotic",
    :"Nurturing",
    :"Perceptive",
    :"Photographer's Eye",
    :"Savvy Sculptor",
    :"Unstable",
    :"Virtuoso",
    :"Athletic (trait)",
    :"Brave",
    :"Clumsy",
    :"Couch Potato",
    :"Coward",
    :"Disciplined",
    :"Heavy Sleeper",
    :"Hydrophobic",
    :"Light Sleeper",
    :"Lucky",
    :"Loves the Cold",
    :"Loves the Heat",
    :"Loves To Swim",
    :"Neat",
    :"Never Nude",
    :"Sailor",
    :"Slob",
    :"Unlucky",
    :"Born Salesperson",
    :"Brooding",
    :"Charismatic",
    :"Commitment Issues",
    :"Dislikes Children",
    :"Diva",
    :"Dramatic",
    :"Easily Impressed",
    :"Flirty",
    :"Friendly (trait)",
    :"Good Sense of Humor",
    :"Great Kisser",
    :"Grumpy",
    :"Hopeless Romantic",
    :"Inappropriate",
    :"Irresistible",
    :"Loner",
    :"Loser",
    :"Mean Spirited",
    :"Mooch",
    :"Natural Born Performer",
    :"No Sense of Humor",
    :"Party Animal",
    :"Proper",
    :"Schmoozer",
    :"Shy",
    :"Snob",
    :"Social Butterfly",
    :"Socially Awkward",
    :"Supernatural Fan",
    :"Supernatural Skeptic",
    :"Unflirty",
    :"Adventurous",
    :"Ambitious",
    :"Angler",
    :"Animal Lover",
    :"Bot Fan",
    :"Cat Person",
    :"Childish",
    :"Daredevil",
    :"Dog Person",
    :"Eco-Friendly",
    :"Equestrian",
    :"Evil",
    :"Family-Oriented",
    :"Frugal",
    :"Good",
    :"Hates the Outdoors",
    :"Hot-Headed",
    :"Kleptomaniac",
    :"Loves the Outdoors",
    :"Night Owl",
    :"Over-Emotional",
    :"Perfectionist",
    :"Rebellious",
    :"Star Quality",
    :"Technophobe",
    :"Vegetarian",
    :"Vehicle Enthusiast",
    :"Workaholic",
    :"Allergic to Fur",
    :"Cultured",
    :"Easy Going",
    :"Flip Flopper",
    :"Gadget Geek",
    :"Hyperactive",
    :"Loves Water",
    :"Megalomaniac",
    :"Outgoing",
    :"Paranoid",
    :"People Pleaser",
    :"Procrastinator",
    :"Shy",
    :"Witty"
]

aspirations = [
    :"Become an Astronaut",
    :"Become a Creature-Robot Cross Breeder",
    :"Become a Master Thief",
    :"Become a Superstar Athlete",
    :"Celebrated Five-Star Chef",
    :"CEO of a Mega-Corporation",
    :"Chess Legend",
    :"Forensic Specialist: Dynamic DNA Profiler",
    :"Gold Digger",
    :"Golden Tongue, Golden Fingers",
    :"Heartbreaker",
    :"Hit Movie Composer",
    :"Illustrious Author",
    :"International Super Spy",
    :"Jack of All Trades",
    :"Leader of the Free World",
    :"Living in the Lap of Luxury",
    :"Master of the Arts",
    :"Perfect Mind, Perfect Body",
    :"Presenting the Perfect Private Aquarium",
    :"Professional Author",
    :"Renaissance Sim",
    :"Rock Star",
    :"Star News Anchor",
    :"Super Popular",
    :"Surrounded by Family",
    :"Swimming in Cash",
    :"The Culinary Librarian",
    :"The Emperor of Evil",
    :"The Perfect Garden",
    :"The Tinkerer",
    :"World Renowned Surgeon",
    :"Bottomless Nectar Cellar",
    :"Great Explorer",
    :"Martial Arts Master",
    :"Physical Perfection",
    :"Private Museum",
    :"Seasoned Traveler",
    :"Visionary",
    :"World-Class Gallery",
    :"Descendant of da Vinci",
    :"Fashion Phenomenon",
    :"Firefighter Super Hero",
    :"Home Design Hotshot",
    :"Monster Maker",
    :"Paranormal Profiteer",
    :"Pervasive Private Eye",
    :"Possession is Nine Tenths of the Law",
    :"Distinguished Director",
    :"Lifestyle of the Rich and Famous",
    :"Master Mixologist",
    :"Master Romancer",
    :"One Sim Band",
    :"Superstar Actor",
    :"The Animal Rescuer",
    :"The Ark Builder",
    :"The Canine Companion",
    :"The Cat Herder",
    :"The Fairy Tale Finder",
    :"The Jockey",
    :"The Zoologist",
    :"Master Acrobat",
    :"Master Magician",
    :"Vocal Legend",
    :"Alchemy Artisan",
    :"Celebrity Psychic",
    :"Greener Gardens",
    :"Leader of the Pack",
    :"Magic Makeover",
    :"Master of Mysticism",
    :"Mystic Healer",
    :"Turn the Town",
    :"Zombie Master",
    :"Blog Artist",
    :"Major Master",
    :"Perfect Student",
    :"Reach Max Influence with All Social Groups",
    :"Scientific Specialist",
    :"Street Credible",
    :"Deep Sea Diver",
    :"Grand Explorer",
    :"Resort Empire",
    :"Seaside Savior",
    :"High Tech Collector",
    :"More than a Machine",
    :"Made the Most of my Time"
]

relationships = [
    :"Yes, this sim's parent",
    :"Yes, this sim's sibling",
    :"Yes, this sim's partner",
    :"Yes, this sim's child",
    :"Yes, this sim's friend",
    :"Yes, this sim's roommate",
    :"Yes, this sim's unrequited love",
    :"Yes, this sim's best friend",
    :"Yes, this sim's lover",
    :"Yes, this sim's bitter partner",
    :"Yes, this sim's mortal enemy"
]

jobs = [
    :"Game Development (University Life)",
    :"Art Appraiser (University Life)",
    :"Sports Agent (University Life)",
    :"Daycare (Generations)",
    :"Astronomer (Into the Future)",
    :"Bot Arena (Into the Future)",
    :"Bot Builder (Into the Future)",
    :"Magician (Showtime)",
    :"Singer (Showtime)",
    :"Fortune Teller (Fortune Teller)",
    :"Scuba Diver (Island Paradise)",
    :"Lifeguard (Island Paradise)",
    :"Gardener (Ambitions)",
    :"Inventor (Ambitions)",
    :"Investigator (Ambitions)",
    :"Writer (Ambitions)",
    :"Painter (Ambitions)",
    :"Angler (Ambitions)",
    :"Sculptor (Ambitions)",
    :"Ghost Hunter (Ambitions)",
    :"Architecture (Ambitions)",
    :"Firefighter (Ambitions)",
    :"Education (Ambitions)",
    :"Fashion (Ambitions)",
    :"Grocery Store Clerk",
    :"Spa Specialist",
    :"Music",
    :"Military",
    :"Bookstore Clerk",
    :"Mausoleum Clerk",
    :"Receptionist",
    :"Journalism",
    :"Business",
    :"Athletic",
    :"Law Enforcement",
    :"Medicine",
    :"Science",
    :"Politics",
    :"Culinary",
    :"Criminal",
    :"Horseman (Pets)",
    :"Film (Late Night)",
    :"Band (Late Night)",
    :"Alien Test Subject (Seasons)",
    :"Nectar Maker (World Adventures)",
    :"Photographer (World Adventures)",
    :"Acrobat (Showtime)",
    :"Alchemist (Supernatural)"
]

foods = [
    :"Autumn Salad",
    :"Cheesesteak",
    :"Cobbler",
    :"Cookies",
    :"Dim Sum",
    :"Fish and Chips",
    :"French Toast",
    :"Fruit Parfait",
    :"Goopy Carbonara",
    :"Grilled Cheese",
    :"Grilled Salmon",
    :"Hamburger",
    :"Hot Dog",
    :"Key Lime Pie",
    :"Lobster Thermidor",
    :"Mac and Cheese",
    :"Ratatouille",
    :"Pancakes",
    :"Peanut Butter and Jelly",
    :"Spaghetti",
    :"Stu Surprise",
    :"Sushi",
    :"Tri-Tip Steak",
    :"Waffles",
    :"Crepes",
    :"Egg Rolls",
    :"Falafel",
    :"Frogs Legs",
    :"Shawarma",
    :"Stir-Fry",
    :"O Positive",
    :"Cheese Tofu Steak",
    :"Fried Peanut Butter and Banana Sandwich",
    :"Spaghetti with Veggie Sauce",
    :"Tofu Dog",
    :"Tri-Tip Tofu Steak",
    :"Vegetarian Dim Sum",
    :"Vegetarian Fish and Chips",
    :"Vegetarian Grilled Salmon",
    :"Veggi Rolls",
    :"Veggie Burger",
    :"Vegetarian Lobster Thermidor",
    :"Aloo Masala Curry",
    :"Ceviche",
    :"Chili Con Carne",
    :"Firecracker Shrimp",
    :"Firecracker Tofu",
    :"Mushroom Omelette",
    :"Porcini Risotto",
    :"Potato and Truffle Torte",
    :"Vegetarian Chili",
    :"Pumpkin Pie",
    :"Kelp"
]

colours = [
    :"Aqua",
    :"Black",
    :"Blue",
    :"Green",
    :"Grey",
    :"Hot Pink",
    :"Irish Green",
    :"Lilac",
    :"Lime",
    :"Orange",
    :"Pink",
    :"Purple",
    :"Red",
    :"Sea Foam",
    :"Spice Brown",
    :"Spiceberry",
    :"Turquoise",
    :"Violet",
    :"White",
    :"Yellow"
]

music = [
    :"Classical",
    :"Custom",
    :"Electronica",
    :"Indie",
    :"Kids",
    :"Latin",
    :"Pop",
    :"Chinese",
    :"Egyptian",
    :"French",
    :"Roots",
    :"Soul",
    :"Rockabilly",
    :"Hip-Hop",
    :"Country Music",
    :"R&B",
    :"Songwriter",
    :"Dark Wave",
    :"Disco",
    :"Rap",
    :"Rock",
    :"Geek Rock",
    :"Beach Party",
    :"Island Life",
    :"Epic",
    :"Spooky",
    :"Western",
    :"DigiTunes"
]

sim = {
    sim: {
        title: 'Gender',
        options: genders
    },
    hair_colour: {
        options: hair_colours
    },
    eye_colour: {
        options: eye_colours
    },
    style: {
        options: styles
    },
    favourite_music: {
        options: music
    },
    favourite_food: {
        options: foods
    },
    favourite_color: {
        options: colours
    },
    traits: {
        min: 5,
        options: traits
    },
    lifetime_wish: {
        options: aspirations
    },
    career_path: {
        help: "This will probably conflict with your aspiration, complete that first before moving on to your assigned job.\nThis assumes you have all expansions, reroll if you don't have access to a career.",
        options: jobs
    },
    another_sim: {
        title: 'Another sim?',
        help: "Hit the big reroll button above to create your next sim, don't forget to create this one first!",
        options: [
            relationships,
            :"No, your family is complete"
        ]
    }
}

GAMES[:the_sims_3] = {
    buy_link: 'http://www.amazon.co.uk/gp/product/B0015YDH6O/ref=as_li_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B0015YDH6O&linkCode=as2&tag=talefromthefo-21&linkId=EOLFBWXPPSSBX5DX',
    site: 'amazon',
    title: 'The Sims 3',
    generator_title: 'Sim',
    background: 'sims3.jpg',
    added: Date.strptime('20150424',"%Y%m%d"),
    last_updated: Date.strptime('20150424',"%Y%m%d"),
    columns: sim
}